import type { FieldDef } from '../resource/form';

/** Policy intent fields (POLICY_ENGINE.md §1.1) as editor inputs. */
export const POLICY_FORM_FIELDS: FieldDef[] = [
  { name: 'name', label: 'Name', type: 'text', required: true },
  { name: 'description', label: 'Description', type: 'textarea' },
  {
    name: 'scope_type',
    label: 'Scope type',
    type: 'select',
    required: true,
    options: [
      { value: 'user', label: 'User' },
      { value: 'group', label: 'Group' },
      { value: 'site', label: 'Site' },
      { value: 'temporary', label: 'Temporary' },
    ],
  },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    options: [
      { value: 'draft', label: 'Draft' },
      { value: 'active', label: 'Active' },
      { value: 'retired', label: 'Retired' },
    ],
  },
  {
    name: 'site_id',
    label: 'Site',
    type: 'select',
    nullable: true,
    optionsFrom: { path: '/api/v1/orgs/{orgId}/sites', label: (r) => String(r.name ?? r.id) },
  },
  { name: 'priority', label: 'Priority', type: 'number' },
  { name: 'is_default', label: 'Default policy for the organization', type: 'checkbox' },
  {
    name: 'download_rate_kbps',
    label: 'Download rate (kbps)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  { name: 'upload_rate_kbps', label: 'Upload rate (kbps)', type: 'number', min: 0, nullable: true },
  {
    name: 'burst_download_kbps',
    label: 'Burst download (kbps)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  {
    name: 'burst_upload_kbps',
    label: 'Burst upload (kbps)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  { name: 'burst_duration_s', label: 'Burst duration (s)', type: 'number', min: 0, nullable: true },
  {
    name: 'quota_daily_bytes',
    label: 'Daily quota (bytes)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  {
    name: 'quota_monthly_bytes',
    label: 'Monthly quota (bytes)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  {
    name: 'quota_total_bytes',
    label: 'Total quota (bytes)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  {
    name: 'session_timeout_s',
    label: 'Session timeout (s)',
    type: 'number',
    min: 0,
    nullable: true,
  },
  { name: 'idle_timeout_s', label: 'Idle timeout (s)', type: 'number', min: 0, nullable: true },
  {
    name: 'max_concurrent_sessions',
    label: 'Max concurrent sessions',
    type: 'number',
    min: 0,
    nullable: true,
  },
  { name: 'max_devices', label: 'Max devices', type: 'number', min: 0, nullable: true },
  { name: 'valid_from', label: 'Valid from', type: 'datetime', nullable: true },
  { name: 'valid_until', label: 'Valid until', type: 'datetime', nullable: true },
  { name: 'vlan_id', label: 'VLAN id', type: 'number', min: 1, max: 4094, nullable: true },
  {
    name: 'schedule_id',
    label: 'Schedule',
    type: 'select',
    nullable: true,
    optionsFrom: { path: '/api/v1/orgs/{orgId}/schedules', label: (r) => String(r.name ?? r.id) },
  },
];

/** Enforcement fields shown in the enforceability preview when set in the draft. */
export const ENFORCEMENT_FIELDS = [
  'download_rate_kbps',
  'upload_rate_kbps',
  'burst_download_kbps',
  'burst_upload_kbps',
  'burst_duration_s',
  'quota_daily_bytes',
  'quota_monthly_bytes',
  'quota_total_bytes',
  'session_timeout_s',
  'idle_timeout_s',
  'max_concurrent_sessions',
  'max_devices',
  'valid_from',
  'valid_until',
  'schedule_id',
  'vlan_id',
] as const;
