/**
 * NAS clients (D-035: each NAS records its engine adapter). The shared secret is generated by
 * the API and shown exactly once after create / rotate.
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import { useState } from 'react';
import { api, newIdempotencyKey } from '../../api/client';
import type { Row } from '../../api/types';
import { Dialog } from '../../components/Dialog';
import { ProblemAlert } from '../../components/ProblemAlert';
import { SecretOnce } from '../../components/SecretOnce';
import { Badge, Button } from '../../components/ui';
import { ADAPTER_KEYS, ADAPTER_LABELS } from '../../lib/adapterStatus';
import { useAuth } from '../../lib/auth';
import { display, formatDateTime, str } from '../../lib/format';
import { can, canPlatform } from '../../lib/permissions';
import type { FieldDef } from '../resource/form';
import { ResourcePage, type ResourceConfig } from '../resource/ResourcePage';
import { PostbackProfileEditor } from './PostbackProfileEditor';
import { MERAKI_ADAPTER_KEY, MerakiCloudRadiusNotice, SetupGuideButton } from './MerakiCloudRadius';

const ADAPTER_OPTIONS = ADAPTER_KEYS.map((k) => ({
  value: k,
  label: `${ADAPTER_LABELS[k]} (${k})`,
}));

function RotateSecret({ row, orgId }: { row: Row; orgId: string }) {
  const [open, setOpen] = useState(false);
  const [secret, setSecret] = useState<string | null>(null);
  const [key] = useState(newIdempotencyKey);
  const rotate = useMutation({
    mutationFn: () =>
      api('post', '/api/v1/orgs/{orgId}/nas/{id}/rotate-secret', {
        params: { orgId, id: row.id },
        idempotencyKey: key,
      }),
    onSuccess: (res) => {
      const value = (res as Record<string, unknown>).secret;
      if (typeof value === 'string') setSecret(value);
    },
  });
  return (
    <>
      <Button size="sm" onClick={() => setOpen(true)}>
        Rotate secret
      </Button>
      <Dialog
        open={open}
        title={`Rotate RADIUS secret: ${str(row.name ?? row.id)}`}
        onClose={() => {
          setOpen(false);
          setSecret(null);
          rotate.reset();
        }}
      >
        {secret ? (
          <SecretOnce
            title="New RADIUS shared secret"
            value={secret}
            description="Configure this on the NAS now. The previous secret stops working immediately."
            onDone={() => {
              setOpen(false);
              setSecret(null);
            }}
          />
        ) : (
          <div className="space-y-3 text-sm">
            <p>
              A new shared secret is generated and the current one is invalidated. RADIUS requests
              from this NAS fail until the device is updated.
            </p>
            <ProblemAlert error={rotate.error} />
            <div className="flex justify-end gap-2">
              <Button onClick={() => setOpen(false)}>Cancel</Button>
              <Button variant="danger" busy={rotate.isPending} onClick={() => rotate.mutate()}>
                Rotate secret
              </Button>
            </div>
          </div>
        )}
      </Dialog>
    </>
  );
}

interface GuideStep {
  id: string;
  title: string;
  setting: string;
  value: string;
}

/** Cycle C: "how to configure this device" steps (filled values; secrets stay placeholders). */
function SetupGuide({ row, orgId }: { row: Row; orgId: string }) {
  const [open, setOpen] = useState(false);
  const guide = useQuery({
    queryKey: ['nas-setup-guide', orgId, row.id],
    enabled: open,
    queryFn: () =>
      api('get', '/api/v1/orgs/{orgId}/nas/{id}/setup-guide', { params: { orgId, id: row.id } }),
  });
  const steps = ((guide.data as Record<string, unknown> | undefined)?.steps ?? []) as GuideStep[];
  return (
    <>
      <Button size="sm" onClick={() => setOpen(true)}>
        Setup guide
      </Button>
      <Dialog
        open={open}
        title={`Setup guide: ${str(row.name ?? row.id)}`}
        onClose={() => setOpen(false)}
      >
        <div className="space-y-3 text-sm">
          <ProblemAlert error={guide.error} />
          {steps.length === 0 && !guide.isLoading ? (
            <p>No guide for this adapter (or the external portal profile is not set).</p>
          ) : (
            <ol className="list-decimal space-y-2 pl-5">
              {steps.map((s) => (
                <li key={s.id}>
                  <span className="font-medium">{s.title}</span>
                  <span className="block text-xs text-subtle">{s.setting}</span>
                  <code className="block break-all text-xs">{s.value}</code>
                </li>
              ))}
            </ol>
          )}
          <p className="text-xs text-subtle">
            Values in &lt;ANGLE_BRACKETS&gt; are placeholders: the RADIUS secret is shown only when
            the NAS is created or its secret rotated.
          </p>
        </div>
      </Dialog>
    </>
  );
}

export function NasPage() {
  const { me } = useAuth();
  const adapterField: FieldDef = {
    name: 'adapter_key',
    label: 'Adapter',
    type: 'select',
    required: true,
    options: ADAPTER_OPTIONS,
    hint: 'The engine adapter that translates policies for this NAS (D-035). Third-party APs on an 802.1X or MAC-auth SSID use the generic adapter; third-party captive portals (Cambium, Aruba, Cisco, …) use the external captive portal adapter; register their AP MACs under Access points. Cisco Meraki splash sign-on uses meraki-splash (RADIUS from the Meraki Cloud; leave NAS IP empty).',
  };

  const fields: FieldDef[] = [
    { name: 'name', label: 'Name', type: 'text', required: true },
    {
      name: 'site_id',
      label: 'Site',
      type: 'select',
      required: true,
      optionsFrom: { path: '/api/v1/orgs/{orgId}/sites', label: (r) => str(r.name ?? r.id) },
    },
    {
      name: 'nas_ip',
      label: 'NAS IP',
      type: 'text',
      nullable: true,
      hint: 'Source IP of RADIUS packets. Required for every adapter except Cisco Meraki (meraki-splash), whose RADIUS comes from the Meraki Cloud: leave it empty there.',
    },
    {
      name: 'nas_identifier',
      label: 'NAS-Identifier',
      type: 'text',
      nullable: true,
      hint: 'Cisco Meraki: leave empty. ECLOUD generates ecloud-<16 hex> (read-only); set it as the custom NAS-ID in Meraki. Requests with another NAS-Identifier are rejected.',
    },
    {
      name: 'das_host',
      label: 'Meraki Disconnect host',
      type: 'text',
      nullable: true,
      hint: 'Cisco Meraki only: the nNNN.meraki.com host from your Dashboard URL (Disconnect, UDP 3799; REQUIRES_DEVICE_TEST).',
    },
    adapterField,
    // Cycle C: post-back profile editor, only for the external captive portal adapter.
    {
      name: 'adapter_config',
      label: 'External captive portal profile',
      type: 'custom',
      visibleWhen: (v) => v.adapter_key === 'external-portal-postback',
      render: ({ value, error, onChange }) => (
        <PostbackProfileEditor value={value} error={error} onChange={onChange} />
      ),
    },
    {
      name: 'network_device_id',
      label: 'Network device',
      type: 'select',
      nullable: true,
      optionsFrom: {
        path: '/api/v1/orgs/{orgId}/network-devices',
        label: (r) => str(r.serial ?? r.id),
      },
    },
    {
      name: 'coa_port',
      label: 'CoA port',
      type: 'number',
      min: 1,
      max: 65535,
      nullable: true,
      hint: 'Disconnect/CoA port on the NAS. Left empty, MikroTik NAS get the RouterOS default 1700.',
    },
    {
      name: 'require_message_authenticator',
      label: 'Require Message-Authenticator',
      type: 'checkbox',
      defaultValue: true,
    },
    {
      name: 'hotspot_address',
      label: 'Hotspot address',
      type: 'text',
      nullable: true,
      hint: 'MikroTik: the router HotSpot interface IP (private IPv4), e.g. the address in its login page link. Required for MikroTik; the portal only sends logins there.',
    },
    {
      name: 'hotspot_port',
      label: 'Hotspot port',
      type: 'number',
      min: 1,
      max: 65535,
      nullable: true,
      hint: 'Optional: the port of the login page when it is not the default 80 / 443.',
    },
    // Review F3: lab mode needs the platform permission; hidden from everyone else.
    ...(canPlatform(me, 'platform:adapter:manage')
      ? [
          {
            name: 'device_test_attributes',
            label: 'Device-test attributes (lab only)',
            type: 'checkbox',
            defaultValue: false,
            hint: 'WARNING: lab use only. Sends reply attributes that still REQUIRE DEVICE TEST (rate limit, timeouts, quota) to this NAS so a lab test can check them. They become live for every user of this NAS; nothing is marked verified. Every change is audited.',
          } satisfies FieldDef,
        ]
      : []),
  ];
  const editFields: FieldDef[] = [
    ...fields,
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: [
        { value: 'active', label: 'Active' },
        { value: 'disabled', label: 'Disabled' },
      ],
    },
  ];

  const config: ResourceConfig = {
    title: 'NAS clients',
    siteFilter: true,
    singular: 'NAS client',
    description: (
      <div className="space-y-2">
        <p>
          RADIUS clients (access points / gateways). The shared secret is shown once when the NAS is
          created or its secret rotated.
        </p>
        <MerakiCloudRadiusNotice />
      </div>
    ),
    path: '/api/v1/orgs/{orgId}/nas',
    permissions: {
      read: 'nas:read',
      create: 'nas:create',
      update: 'nas:update',
      delete: 'nas:delete',
    },
    columns: [
      { key: 'name', header: 'Name' },
      { key: 'nas_ip', header: 'IP' },
      { key: 'nas_identifier', header: 'NAS-Identifier' },
      {
        key: 'adapter_key',
        header: 'Adapter',
        render: (r) => <code className="text-xs">{display(r.adapter_key)}</code>,
      },
      {
        key: 'status',
        header: 'Status',
        render: (r) => (
          <Badge tone={r.status === 'active' ? 'success' : 'neutral'}>{str(r.status ?? '—')}</Badge>
        ),
      },
      { key: 'updated_at', header: 'Updated', render: (r) => formatDateTime(r.updated_at) },
    ],
    fields,
    editFields,
    secretOnCreate: {
      key: 'secret',
      title: 'RADIUS shared secret',
      description: 'Configure this on the NAS now. It is shown only once; rotate it if lost.',
    },
    rowActions: (row, { orgId }) => (
      <>
        {/* Cycle E: Meraki rows get the guide with the cloud-RADIUS state and warnings. */}
        {row.adapter_key === MERAKI_ADAPTER_KEY ? (
          <SetupGuideButton row={row} orgId={orgId} />
        ) : (
          <SetupGuide row={row} orgId={orgId} />
        )}
        {can(me, 'nas:secret:rotate', {
          organizationId: orgId,
          siteId: (row.site_id as string) ?? null,
        }) ? (
          <RotateSecret row={row} orgId={orgId} />
        ) : null}
      </>
    ),
  };
  return <ResourcePage config={config} />;
}
