#!/usr/bin/env node
/* global fetch, console */
/**
 * Regenerates the typed API client inputs (committed, reproducible):
 *   src/api/openapi.json  — the API's OpenAPI 3.1 document (stable key order, prettier-formatted)
 *   src/api/schema.d.ts   — `paths` / `components` types emitted by openapi-typescript
 *
 * Source of the document (first match):
 *   --url <http://127.0.0.1:3000/api/v1/openapi.json>   a running API
 *   default                                             the built API (apps/api/dist): routes
 *                                                       are assembled in-process with inert
 *                                                       dependencies; nothing connects to a
 *                                                       database or Redis.
 * Run `npm run build` at the repo root first when using the default source.
 */
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parseArgs } from 'node:util';
import openapiTS, { astToString } from 'openapi-typescript';
import * as prettier from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, '..');
const outDir = resolve(appDir, 'src/api');
const apiDist = resolve(appDir, '../api/dist/index.js');

const { values } = parseArgs({ options: { url: { type: 'string' } } });

async function fromUrl(url) {
  const res = await fetch(url, { headers: { accept: 'application/json' } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.json();
}

async function fromBuiltApi() {
  if (!existsSync(apiDist)) {
    throw new Error(`${apiDist} not found: run \`npm run build\` at the repository root first`);
  }
  const api = await import(pathToFileURL(apiDist).href);
  // Inert configuration: obviously-fake URLs on a closed port; routes are only defined, never run.
  const config = api.loadApiConfig({
    NODE_ENV: 'test',
    LOG_LEVEL: 'silent',
    KV_DRIVER: 'memory',
    DATABASE_URL: 'postgres://127.0.0.1:1/openapi',
    DATABASE_URL_PLATFORM: 'postgres://127.0.0.1:1/openapi',
  });
  const noop = () => undefined;
  const logger = { info: noop, warn: noop, error: noop, debug: noop, trace: noop, fatal: noop };
  logger.child = () => logger;
  const deps = { config, logger, db: {}, dbPlatform: {}, kv: {} };
  return api.buildOpenApiDocument(api.allRoutes(deps), api.API_VERSION);
}

function sortKeys(value) {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((k) => [k, sortKeys(value[k])]),
    );
  }
  return value;
}

const document = values.url ? await fromUrl(values.url) : await fromBuiltApi();
// Paths keep their declaration order (it is meaningful to readers); everything else is sorted.
const stable = { ...sortKeys(document), paths: {} };
for (const [path, item] of Object.entries(document.paths ?? {}))
  stable.paths[path] = sortKeys(item);

const prettierConfig = (await prettier.resolveConfig(resolve(appDir, 'package.json'))) ?? {};
const header =
  '/**\n * GENERATED by apps/admin/scripts/generate-api.mjs from the ECLOUD OpenAPI document.\n' +
  ' * Do not edit by hand: run `npm run generate:api -w @ecloud/admin`.\n */\n';
const types = header + astToString(await openapiTS(stable, { alphabetize: false }));

await mkdir(outDir, { recursive: true });
await writeFile(
  resolve(outDir, 'openapi.json'),
  await prettier.format(JSON.stringify(stable), { ...prettierConfig, parser: 'json' }),
);
await writeFile(
  resolve(outDir, 'schema.d.ts'),
  await prettier.format(types, { ...prettierConfig, parser: 'typescript' }),
);
console.error(
  `generated src/api/openapi.json and src/api/schema.d.ts (${Object.keys(stable.paths).length} paths, API ${stable.info?.version ?? '?'})`,
);
