/**
 * Test-only mock vendor controller (Cycle D, @ecloud/vendor-api tests and the api / worker
 * integration tests): a local HTTPS server on 127.0.0.1 with a throw-away CA and
 * leaf certificate generated by `openssl` at test time (no key material is committed). Nothing
 * here talks to a real vendor controller.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createServer, type Server } from 'node:https';
import type { IncomingMessage, ServerResponse } from 'node:http';
import type { AddressInfo } from 'node:net';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { X509Certificate } from 'node:crypto';

export interface TestPki {
  readonly caPem: string;
  readonly leafCertPem: string;
  readonly leafKeyPem: string;
  /** Independent self-signed certificate (not issued by `caPem`). */
  readonly otherCertPem: string;
  readonly otherKeyPem: string;
  /** SHA-256 fingerprint (`AB:CD:…`) of the leaf. */
  readonly leafFingerprint: string;
  readonly otherFingerprint: string;
}

let cached: TestPki | null = null;

/** Leaf valid for DNS `controller.test` and IP 127.0.0.1, issued by a test CA. */
export function testPki(): TestPki {
  if (cached !== null) return cached;
  const dir = mkdtempSync(join(tmpdir(), 'ecloud-vendor-pki-'));
  const ossl = (...args: string[]): void => {
    execFileSync('openssl', args, { cwd: dir, stdio: 'ignore' });
  };
  try {
    const ec = ['-newkey', 'ec', '-pkeyopt', 'ec_paramgen_curve:prime256v1', '-nodes'];
    ossl(
      'req',
      '-x509',
      ...ec,
      '-keyout',
      'ca.key',
      '-out',
      'ca.pem',
      '-days',
      '2',
      '-subj',
      '/CN=ECLOUD Test CA',
      '-addext',
      'basicConstraints=critical,CA:TRUE',
      '-addext',
      'keyUsage=critical,keyCertSign,cRLSign',
    );
    ossl('req', ...ec, '-keyout', 'leaf.key', '-out', 'leaf.csr', '-subj', '/CN=controller.test');
    writeFileSync(
      join(dir, 'leaf.ext'),
      'subjectAltName=DNS:controller.test,IP:127.0.0.1\nbasicConstraints=CA:FALSE\nextendedKeyUsage=serverAuth\n',
    );
    ossl(
      'x509',
      '-req',
      '-in',
      'leaf.csr',
      '-CA',
      'ca.pem',
      '-CAkey',
      'ca.key',
      '-CAcreateserial',
      '-out',
      'leaf.pem',
      '-days',
      '2',
      '-extfile',
      'leaf.ext',
    );
    ossl(
      'req',
      '-x509',
      ...ec,
      '-keyout',
      'other.key',
      '-out',
      'other.pem',
      '-days',
      '2',
      '-subj',
      '/CN=controller.test',
      '-addext',
      'subjectAltName=DNS:controller.test,IP:127.0.0.1',
    );
    const read = (f: string): string => readFileSync(join(dir, f), 'utf8');
    const leafCertPem = read('leaf.pem');
    const otherCertPem = read('other.pem');
    cached = {
      caPem: read('ca.pem'),
      leafCertPem,
      leafKeyPem: read('leaf.key'),
      otherCertPem,
      otherKeyPem: read('other.key'),
      leafFingerprint: new X509Certificate(leafCertPem).fingerprint256,
      otherFingerprint: new X509Certificate(otherCertPem).fingerprint256,
    };
    return cached;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

export interface RecordedRequest {
  readonly method: string;
  readonly url: string;
  readonly headers: IncomingMessage['headers'];
  readonly body: string;
}

export type MockHandler = (req: RecordedRequest, res: ServerResponse) => void | Promise<void>;

export interface MockController {
  readonly port: number;
  readonly requests: RecordedRequest[];
  handler: MockHandler;
  close(): Promise<void>;
}

export async function startMockController(
  options: { cert?: 'leaf' | 'other'; handler?: MockHandler } = {},
): Promise<MockController> {
  const pki = testPki();
  const useOther = options.cert === 'other';
  const requests: RecordedRequest[] = [];
  const state: { handler: MockHandler } = {
    handler:
      options.handler ??
      ((_req, res) => {
        res.writeHead(404).end();
      }),
  };
  const server: Server = createServer(
    {
      cert: useOther ? pki.otherCertPem : pki.leafCertPem,
      key: useOther ? pki.otherKeyPem : pki.leafKeyPem,
    },
    (req, res) => {
      const chunks: Buffer[] = [];
      req.on('data', (c: Buffer) => chunks.push(c));
      req.on('end', () => {
        const recorded: RecordedRequest = {
          method: req.method ?? '',
          url: req.url ?? '',
          headers: req.headers,
          body: Buffer.concat(chunks).toString('utf8'),
        };
        requests.push(recorded);
        void Promise.resolve(state.handler(recorded, res)).catch(() => {
          res.destroy();
        });
      });
    },
  );
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const port = (server.address() as AddressInfo).port;
  return {
    port,
    requests,
    get handler() {
      return state.handler;
    },
    set handler(h: MockHandler) {
      state.handler = h;
    },
    close: () =>
      new Promise<void>((resolve) => {
        server.closeAllConnections();
        server.close(() => resolve());
      }),
  };
}

export function json(
  res: ServerResponse,
  status: number,
  body: unknown,
  headers: Record<string, string | string[]> = {},
): void {
  const text = JSON.stringify(body);
  res.writeHead(status, {
    'content-type': 'application/json',
    'content-length': Buffer.byteLength(text),
    ...headers,
  });
  res.end(text);
}

/** Resolver mapping every name to loopback (tests only). */
export const loopbackResolver = (): Promise<{ address: string; family: number }[]> =>
  Promise.resolve([{ address: '127.0.0.1', family: 4 }]);

/** Address policy override that admits loopback (tests only; production never passes one). */
export const allowLoopback = (address: string): boolean => address === '127.0.0.1';
