import { uuidv7 } from 'uuidv7';

/** Any RFC 9562 UUID (versions 1-8), lower- or upper-case. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const UUID_V7_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Generates a new application-side UUID v7 (time-ordered, DATABASE_DESIGN.md §1).
 * Ids are generated by the application, never by the database.
 */
export function newId(): string {
  return uuidv7();
}

/** True when `value` is a well-formed RFC 9562 UUID string of any version. */
export function isUuid(value: unknown): value is string {
  return typeof value === 'string' && UUID_RE.test(value);
}

/** True when `value` is a well-formed UUID **v7** string. */
export function isUuidV7(value: unknown): value is string {
  return typeof value === 'string' && UUID_V7_RE.test(value);
}
